name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: main
    - name: Setup Docker CLI
      uses: docker/setup-docker@v2
      with:
        version: latest

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghactiontest:latest
          ghactiontest-${{ env.random_string }}:latest
        context: .
        platform: |
          linux/amd64
          linux/arm64
          linux/arm/v7

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Generate random string
      id: random_string
      run: echo "random_string=$(date +%s | shasum | base64 | head -c 10)" >> env.env

    - name: Set env var
      uses: actions/set-env@v1
      with:
        env: env.env

    - name: Push Docker Image
      uses: docker/push-action@v1
      with:
        tags: |
          ghactiontest:latest
          ghactiontest-${{ env.random_string }}:latest

