name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA }}
  IMAGE_NAME: gha-playground

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Docker BuildX
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        echo "${{ env.DOCKER_PASS }}" | docker login -u "${{ env.DOCKER_USER }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
                            -t "${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:master" \
                            -t "${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:master-$GITHUB_SHA_SHORT" \
                            --push .

    - name: Push Docker Image
      run: |
        docker push "${{ env.DOCKER_USER }}/image-name:master"
        docker push "${{ env.DOCKER_USER }}/image-name:master-$GITHUB_SHA_SHORT"

