name: Docker Build & Push to Dockerhub

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA_SHORT }}
  DOCKER_REPO: gha-playground

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
                              -t ${{ env.DOCKER_REPO }}:master \
                              -t ${{ env.DOCKER_REPO }}:master-${{ env.GITHUB_SHA_SHORT }} \
                              .

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Push Docker Images to Dockerhub
        run: |
          docker push ${{ env.DOCKER_REPO }}:master
          docker push ${{ env.DOCKER_REPO }}:master-${{ env.GITHUB_SHA_SHORT }}
