name: Docker Image Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  IMAGE_NAME: ghactiontest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build Multi-Arch Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:latest-${{ env.GITHUB_SHA }}
          build-args: |
            --platform linux/amd64,linux/arm64,linux/arm/v7
            --progress plain
            --build-arg GITHUB_SHA=${{ env.GITHUB_SHA }}
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }}
            --build-arg VCS_REF=${{ env.VCS_REF }}

      - name: Generate Github Commit Short SHA
        run: echo "GITHUB_SHA=${{ env.GITHUB_SHA }}" >> env.properties
        id: sha-env
      
      - name: Publish to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest-${{ env.GITHUB_SHA }}
