name: Docker Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Docker CLI
      uses: docker/setup-docker-cli@v1
      with:
        docker-version: 19.03

    - name: Login to Docker Hub
      run: |
        echo ${DOCKER_PWD} | docker login -u ${DOCKER_USER} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          -t ${DOCKER_USER}/image:latest \
          -t ${DOCKER_USER}/image:latest-${{ env.GITHUB_SHA_SHORT }} \
          --push \
          .

    - name: Clean up
      run: |
        docker system prune -f
