name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 0 * * 6'
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker CLI
      uses: docker/setup-docker-cli@v2
      with:
        docker-version: latest

    - name: Login to Docker Hub
      run: echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --tag $DOCKER_USER/image:latest --tag $DOCKER_USER/image:${{ env.GITHUB_SHA }} .
        
    - name: Push Docker Image
      run: |
        docker push $DOCKER_USER/image:latest
        docker push $DOCKER_USER/image:${{ env.GITHUB_SHA }}
