name: Docker Image Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/workflows/*
      - Dockerfile
  schedule:
    - cron: '00 0 * * 6'
  workflow_dispatch:

env:
  GITHUB_SHA_SHORT: ${{ short_sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y qemu-user-static
        echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        docker buildx create --use --name mybuilder
        docker buildx inspect --bootstrap

    - name: Build Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t myimage:latest .
        echo "${{ secrets.DOCKER_PWD }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push -t "${{ secrets.DOCKER_USER }}/myimage:latest" .
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push -t "${{ secrets.DOCKER_USER }}/myimage:latest-${{ env.GITHUB_SHA_SHORT }}" .
