name: Build and push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA_SHORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: 1
      run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64,linux/arm/v7 \
        --push \
        -t "${{ secrets.DOCKER_USER }}/gha-playground:master" \
        -t "${{ secrets.DOCKER_USER }}/gha-playground:master-$GITHUB_SHA_SHORT" \
        .
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
        
    - name: Push to DockerHub
      uses: docker/push-action@v1
      with:
        tags: "${{ secrets.DOCKER_USER }}/gha-playground:master,${{ secrets.DOCKER_USER }}/gha-playground:master-$GITHUB_SHA_SHORT"
