name: Docker Image Build and Push

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'
      - 'Dockerfile'
    branches:
      - main

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  IMAGE_NAME: my_image
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA | shorten }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build Multi-Arch Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}
          build-args: |
            --platform linux/amd64,linux/arm64,linux/arm/v7
            --progress plain
            --build-arg GITHUB_SHA=${{ env.GITHUB_SHA }}
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }}
            --build-arg VCS_REF=${{ env.VCS_REF }}

      - name: Publish to Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}
