name: Docker Build Master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/workflows/*
      - Dockerfile
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:
env:
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        registry-mirror: docker.io
    - name: Build Docker Image using Buildx
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          latest
          latest-${{ env.GITHUB_SHA_SHORT }}
        build-args: |
          --build-arg BUILDKIT_INLINE_CACHE=1
        platforms: linux/amd64,linux/arm64,linux/arm/v7

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
