name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * 6'

env:
  IMAGE_NAME: ghactiontest
  RANDOM_TAG: ${{ env.GITHUB_SHA | sha256sum | cut -c1-7 }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Docker CLI
      uses: docker/setup-docker@v21.0.0

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: "${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:latest-${{ env.RANDOM_TAG }}"
        push: true
        push-with-registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
        build-args: |
          --build-arg IMAGE_NAME=${{ env.IMAGE_NAME }}
          --build-arg RANDOM_TAG=${{ env.RANDOM_TAG }}

    - name: Set ARCHS environment variable
      uses: actions/set-env@v2
      with:
        name: ARCHS
        value: linux/amd64,linux/arm64,linux/arm/v7

    - name: Set UP_TO_DATE environment variable
      uses: actions/set-env@v2
      with:
        name: UP_TO_DATE
        value: true
  
    - name: Login to DockerHub
      run: |
        echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Docker Build and Push
      run: |
        buildx create --use
        buildx build --platform $ARCHS --push -t $IMAGE_NAME:latest -t $IMAGE_NAME:latest-$RANDOM_TAG .
