name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_SHA }}
        path: github/workflow

    - name: Configure Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.io/${{ secrets.DOCKER_USER }}/ghactiontest:latest,docker.io/${{ secrets.DOCKER_USER }}/ghactiontest:latest-${{ env.GITHUB_SHA }}
        context: .
        dockerfile: Dockerfile
        secrets:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
        buildx: true

    - name: Save Docker Image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: .
