name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: gha-playground
  IMAGE_TAG: master

env:
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA_SHORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-version: latest
        
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-${{ env.GITHUB_SHA_SHORT }}
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
