name: Docker Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 0 * * 6'
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ env.GITHUB_SHA }}
  GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA | cut -c1-7 }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: ${{ env.GITHUB_SHA }}
    - name: Setup Docker CLI
      uses: docker/setup-docker-cli@v2
      with:
        version: latest

    - name: Configure Docker CLI for multi-arch build
      run: |
        echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        docker buildx create --use --name multiarch
        docker buildx inspect --bootstrap

    - name: Build Docker Image
      run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64,linux/arm/v7 \
        --tag ${{ secrets.DOCKER_USER }}/image-name:latest \
        --tag ${{ secrets.DOCKER_USER }}/image-name:latest-${{ env.GITHUB_SHA_SHORT }} \
        --push \
        .

    - name: Clean up Docker CLI
      run: |
        docker buildx rm multiarch
