name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
  GITHUB_SHA_SHORT: ${{ short_sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker setup
      uses: docker/setup-docker@v2021-06-22
      with:
        docker-version: 19.03.13

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PWD }}

    - name: Build Docker Image
      run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -t $DOCKER_USER/ghactest:latest \
        -t $DOCKER_USER/ghactest:latest-$GITHUB_SHA_SHORT \
        --push .

    - name: Clean up
      run: |
        docker system prune -af
