name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/workflows/*
      - Dockerfile
  workflow_dispatch:

env:
  IMAGE_NAME: gha-playground
  IMAGE_TAG: master

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install-default: true
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin  
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        COMMIT_SHA: ${{ env.IMAGE_TAG }}-${{ env.GITHUB_SHA }}
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}
