name: Docker Build Master

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 0 * * 6'
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        registry: docker.io

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build and Push Docker Image
      run: |
        export GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${{ secrets.DOCKER_USER }}/my-image:latest -t ${{ secrets.DOCKER_USER }}/my-image:latest-$GITHUB_SHA_SHORT .
        docker push ${{ secrets.DOCKER_USER }}/my-image
